### Create execution with all steps

POST {{baseUrl}}/executions
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "jobId": "b03ddac3-5033-4bb1-5b46-08dc66907662"
}

### Create execution with specific steps

POST {{baseUrl}}/executions
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "jobId": "29a43f41-d2e4-4e86-62a0-08dbb695de54",
  "stepIds": ["1135cd43-61ca-446c-5deb-08dbb6cadb53"]
}

### Create execution with job parameter overrides

POST {{baseUrl}}/executions
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "jobId": "29a43f41-d2e4-4e86-62a0-08dbb695de54",
  "stepIds": ["79864a73-a819-415a-4ffd-08dbb6976a67"],
  "jobParameterOverrides": [
    {
      "parameterId": "81b2bca5-3398-45b1-953e-08dc4fbd5e4c",
      "parameterValue": {
        "valueType": "Boolean",
        "valueBoolean": true
      }
    }
  ]
}

### Stop job execution

POST {{baseUrl}}/executions/6acf57bd-de45-4f4f-8f57-b3789d5e90b6/stop
x-api-key: {{apiKey}}

### Stop step execution

POST {{baseUrl}}/executions/3cd18bbd-47ea-49ff-9b19-ac554f75673e/steps/4026971a-fa0b-4c6c-9d33-b59c26498384/stop
x-api-key: {{apiKey}}