### All jobs

GET {{baseUrl}}
    /jobs
    ?includeTags=true
x-api-key: {{apiKey}}

### Job by id

GET {{baseUrl}}
    /jobs
    /29a43f41-d2e4-4e86-62a0-08dbb695de54
    ?includeParameters=true
    &includeConcurrencies=true
x-api-key: {{apiKey}}

### Job steps

GET {{baseUrl}}
    /jobs
    /29a43f41-d2e4-4e86-62a0-08dbb695de54
    /steps
    ?includeTags=true
x-api-key: {{apiKey}}

### Job schedules

GET {{baseUrl}}
    /jobs
    /29a43f41-d2e4-4e86-62a0-08dbb695de54
    /schedules
x-api-key: {{apiKey}}

### Step by id

GET {{baseUrl}}
    /jobs
    /steps
    /1919b753-096d-44ca-5df0-08dbb6cadb53
x-api-key: {{apiKey}}