### Create job

POST {{baseUrl}}/jobs
x-api-key: {{apiKey}}
Content-Type: application/json

{
    "JobId": "418c18b9-7086-4774-8412-f9bffa097499",
    "JobName": "API test job",
    "JobDescription": "Job created from API",
    "ExecutionMode": "ExecutionPhase",
    "StopOnFirstError": false,
    "MaxParallelSteps": 10,
    "OvertimeNotificationLimitMinutes": 0,
    "TimeoutMinutes": 0,
    "IsEnabled": true,
    "IsPinned": false
}

### Update job

PUT {{baseUrl}}/jobs
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "JobId": "418c18b9-7086-4774-8412-f9bffa097499",
  "JobName": "API test job renamed",
  "JobDescription": "Job created from API",
  "ExecutionMode": "ExecutionPhase",
  "StopOnFirstError": false,
  "MaxParallelSteps": 10,
  "OvertimeNotificationLimitMinutes": 0,
  "TimeoutMinutes": 0,
  "IsEnabled": true,
  "IsPinned": false
}

### Update job concurrencies

PUT {{baseUrl}}/jobs/418c18b9-7086-4774-8412-f9bffa097499/concurrencies
x-api-key: {{apiKey}}
Content-Type: application/json

[
  { "stepType": "Sql", "maxParallelSteps": 1 },
  { "stepType": "Pipeline", "maxParallelSteps": 2 }
]

### Clear job concurrencies (empty array)

PUT {{baseUrl}}/jobs/418c18b9-7086-4774-8412-f9bffa097499/concurrencies
x-api-key: {{apiKey}}
Content-Type: application/json

[]

### Create job tag

POST {{baseUrl}}/jobs/tags
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "tagId": "4a65701c-38bf-4f69-9739-6517874512a1",
  "tagName": "api-tag",
  "color": "DarkGray",
  "sortOrder": 10
}

### Update job tag

PUT {{baseUrl}}/jobs/tags
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "tagId": "4a65701c-38bf-4f69-9739-6517874512a1",
  "tagName": "api-tag-updated",
  "color": "LightGray",
  "sortOrder": 10
}

### Create job tag relation

POST {{baseUrl}}/jobs/418c18b9-7086-4774-8412-f9bffa097499/tags/4a65701c-38bf-4f69-9739-6517874512a1
x-api-key: {{apiKey}}

### Delete job tag relation

DELETE {{baseUrl}}/jobs/418c18b9-7086-4774-8412-f9bffa097499/tags/4a65701c-38bf-4f69-9739-6517874512a1
x-api-key: {{apiKey}}

### Delete job tag

DELETE {{baseUrl}}/jobs/tags/4a65701c-38bf-4f69-9739-6517874512a1
x-api-key: {{apiKey}}

### Delete job

DELETE {{baseUrl}}/jobs/418c18b9-7086-4774-8412-f9bffa097499
x-api-key: {{apiKey}}