### All jobs

GET {{baseUrl}}
    /jobs
    ?includeTags=true
x-api-key: {{apiKey}}

### All job tags

GET {{baseUrl}}/jobs/tags
x-api-key: {{apiKey}}

### Job by id

GET {{baseUrl}}
    /jobs
    /418c18b9-7086-4774-8412-f9bffa097499
    ?includeParameters=true
    &includeConcurrencies=true
x-api-key: {{apiKey}}

### Job steps

GET {{baseUrl}}
    /jobs
    /29a43f41-d2e4-4e86-62a0-08dbb695de54
    /steps
    ?includeTags=true
x-api-key: {{apiKey}}

### Job schedules

GET {{baseUrl}}
    /jobs
    /29a43f41-d2e4-4e86-62a0-08dbb695de54
    /schedules
x-api-key: {{apiKey}}

### Job tag by id

GET {{baseUrl}}/jobs/tags/4a65701c-38bf-4f69-9739-6517874512a1
x-api-key: {{apiKey}}