### Update SQL step

PUT {{baseUrl}}/jobs/steps/sql/4cedf210-25ca-43e3-bf8c-08dd3b0d900a
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "stepName": "API test step",
  "stepDescription": null,
  "executionPhase": 10,
  "duplicateExecutionBehaviour": "Allow",
  "isEnabled": true,
  "retryAttempts": 1,
  "retryIntervalMinutes": 1.5,
  "executionConditionExpression": null,
  "stepTagIds": [],
  "timeoutMinutes": 0,
  "sqlStatement": "select @param2",
  "connectionId": "2d8cf992-a71f-4ba3-3127-08dbb695f924",
  "resultCaptureJobParameterId": null,
  "parameters": [
    {
      "parameterId": "abc5d9a6-aa1f-4c93-f793-08dd3d1dba58",
      "parameterName": "@param2",
      "parameterValue": { "valueType": "String", "valueString": "hello world" },
      "useExpression": true,
      "expression": "testParam",
      "inheritFromJobParameterId": null,
      "expressionParameters": [
        {
          "parameterId": null,
          "parameterName": "testParam",
          "inheritFromJobParameterId": "26dcdb06-0cd1-4509-a9f0-08dd3b0d7e56"
        }
      ]
    }
  ],
  "dependencies": [],
  "executionConditionParameters": [],
  "sources": [],
  "targets": []
}

### Update package step

PUT {{baseUrl}}/jobs/steps/package/bdcdeea6-e8f2-4084-8140-08dd3de7e2d6
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "stepName": "API test step",
  "stepDescription": null,
  "executionPhase": 10,
  "duplicateExecutionBehaviour": "Allow",
  "isEnabled": true,
  "retryAttempts": 1,
  "retryIntervalMinutes": 1.5,
  "executionConditionExpression": null,
  "stepTagIds": [],
  "timeoutMinutes": 0,
  "connectionId":  "2d8cf992-a71f-4ba3-3127-08dbb695f924",
  "packageFolderName": "DemoDW",
  "packageProjectName":  "DemoDW_STG_WWI",
  "packageName": "STG_InvoiceLines.dtsx",
  "executeIn32BitMode": true,
  "executeAsLogin": null,
  "parameters": [
    {
      "parameterId": "33fce47a-d8b4-4c96-1a05-08dd3d22c7ff",
      "parameterName": "Incremental",
      "parameterLevel": "Package",
      "parameterValue": { "valueType": "Boolean", "valueBoolean": true },
      "useExpression": false,
      "expression": null,
      "inheritFromJobParameterId": null,
      "expressionParameters": []
    }
  ],
  "dependencies": [
    { "dependentOnStepId": "4cedf210-25ca-43e3-bf8c-08dd3b0d900a", "dependencyType": "OnSucceeded" }
  ],
  "executionConditionParameters": [
    {
      "parameterId": null,
      "parameterName": "paramY",
      "parameterValue": { "valueType": "Int32", "valueInt32": 123 },
      "inheritFromJobParameterId": null
    }
  ],
  "sources": [
    { "dataObjectId": "0026bec9-136d-4dce-f91d-08dbb6976a68", "dataAttributes": [] }
  ],
  "targets": [
    { "dataObjectId": "0026bec9-136d-4dce-f91d-08dbb6976a68", "dataAttributes": ["asd"] },
    { "dataObjectId": "971899b9-6858-4174-34d7-08dbb6cadb55", "dataAttributes": ["asd"] }
  ]
}