### All users

GET {{baseUrl}}/users
x-api-key: {{apiKey}}

### User by id

GET {{baseUrl}}/users/e2d1747e-6ddf-4ebb-a5f5-dfd9fadff4f1
x-api-key: {{apiKey}}

### User jobs

GET {{baseUrl}}/users/e2d1747e-6ddf-4ebb-a5f5-dfd9fadff4f1/jobs
x-api-key: {{apiKey}}

### User data tables

GET {{baseUrl}}/users/e2d1747e-6ddf-4ebb-a5f5-dfd9fadff4f1/datatables
x-api-key: {{apiKey}}

### User subscriptions

GET {{baseUrl}}/users/e2d1747e-6ddf-4ebb-a5f5-dfd9fadff4f1/subscriptions
x-api-key: {{apiKey}}