CREATE PROCEDURE [etlmanager].[ExecutionStepCopy]
	@ExecutionId UNIQUEIDENTIFIER,
	@StepId UNIQUEIDENTIFIER,
    @RetryAttemptIndex INT,
    @Status VARCHAR(50) = 'RUNNING'
AS

INSERT INTO etlmanager.Execution (
	[ExecutionId],
    [JobId],
    [JobName],
    [StepId],
    [StepName],
    [CreatedDateTime],
    [RetryAttemptIndex],
    [StartDateTime],
    [ExecutionStatus],
    [RetryAttempts],
    [RetryIntervalMinutes],
    [TimeoutMinutes],
    [ExecutionPhase],
    [DependencyMode],
    [StepType],
    [SqlStatement],
    [ConnectionId],
    [PackageFolderName],
    [PackageProjectName],
    [PackageName],
    [ExecuteIn32BitMode],
    [PackageOperationId],
    DataFactoryId,
	PipelineName,
    JobToExecuteId,
    JobExecuteSynchronized,
    [CreatedBy],
    [StoppedBy],
    [ScheduleId],
    [ExecutorProcessId]
)
SELECT
	[ExecutionId],
    [JobId],
    [JobName],
    [StepId],
    [StepName],
    [CreatedDateTime],
    [RetryAttemptIndex] = @RetryAttemptIndex,
    [StartDateTime] = GETDATE(),
    [ExecutionStatus] = @Status,
    [RetryAttempts],
    [RetryIntervalMinutes],
    [TimeoutMinutes],
    [ExecutionPhase],
    [DependencyMode],
    [StepType],
    [SqlStatement],
    [ConnectionId],
    [PackageFolderName],
    [PackageProjectName],
    [PackageName],
    [ExecuteIn32BitMode],
    [PackageOperationId],
    DataFactoryId,
	PipelineName,
    JobToExecuteId,
    JobExecuteSynchronized,
    [CreatedBy],
    [StoppedBy],
    [ScheduleId],
    [ExecutorProcessId]
FROM etlmanager.Execution
WHERE ExecutionId = @ExecutionId AND StepId = @StepId AND RetryAttemptIndex = 0