CREATE TABLE [etlmanager].[StepTag]
(
	[StepId] UNIQUEIDENTIFIER NOT NULL,
	[TagId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_StepTag] PRIMARY KEY CLUSTERED ([StepId], [TagId]),
	CONSTRAINT [FK_StepTag_Step] FOREIGN KEY ([StepId]) REFERENCES etlmanager.Step ([StepId]) ON DELETE CASCADE,
	CONSTRAINT [FK_StepTag_Tag] FOREIGN KEY ([TagId]) REFERENCES etlmanager.Tag ([TagId]) ON DELETE CASCADE
)
