CREATE TABLE [etlmanager].[ExecutionStep] (
    [ExecutionId]               UNIQUEIDENTIFIER    NOT NULL CONSTRAINT [FK_ExecutionStep_Execution] FOREIGN KEY REFERENCES [etlmanager].[Execution] ([ExecutionId]),
    [StepId]                    UNIQUEIDENTIFIER    NOT NULL,
    [StepName]                  NVARCHAR(250)       NOT NULL,
    [RetryAttempts]             INT                 NOT NULL,
    [RetryIntervalMinutes]      INT                 NOT NULL,
    [TimeoutMinutes]            INT                 NOT NULL CONSTRAINT [DF_ExecutionStep_TimeoutMinutes] DEFAULT (0),
    [ExecutionPhase]            INT                 NOT NULL,
    [StepType]                  VARCHAR (20)        NOT NULL,
    [SqlStatement]              NVARCHAR (MAX)      NULL,
    [ConnectionId]              UNIQUEIDENTIFIER    NULL,
    [PackageFolderName]         NVARCHAR(128)       NULL,
    [PackageProjectName]        NVARCHAR(128)       NULL,
    [PackageName]               NVARCHAR(260)       NULL,
    [ExecuteIn32BitMode]        BIT                 NOT NULL,
    [ExecuteAsLogin]            NVARCHAR(128)       NULL,
    [DataFactoryId]             UNIQUEIDENTIFIER    NULL,
    [PipelineName]              NVARCHAR(250)       NULL,
    [JobToExecuteId]            UNIQUEIDENTIFIER    NULL,
    [JobExecuteSynchronized]    BIT                 NULL,
    [ExeFileName]               NVARCHAR(1000)      NULL,
    [ExeArguments]              NVARCHAR(MAX)       NULL,
    [ExeWorkingDirectory]       NVARCHAR(1000)      NULL,
    [ExeSuccessExitCode]        INT                 NULL,
    [AppRegistrationId]         UNIQUEIDENTIFIER    NULL,
    [DatasetGroupId]            NVARCHAR(36)        NULL,
    [DatasetId]                 NVARCHAR(36)        NULL,
    [FunctionAppId]             UNIQUEIDENTIFIER    NULL,
    [FunctionUrl]               VARCHAR(1000)       NULL,
    [FunctionInput]             NVARCHAR(MAX)       NULL,
    [FunctionIsDurable]         BIT                 NULL,
    CONSTRAINT [PK_ExecutionStep] PRIMARY KEY CLUSTERED ([ExecutionId] ASC, [StepId] ASC),
    CONSTRAINT [CK_ExecutionStep_StepType] CHECK ([StepType]='SSIS' OR [StepType]='SQL' OR [StepType]='JOB' OR [StepType]='PIPELINE' OR [StepType]='EXE' OR [StepType]='DATASET' OR [StepType]='FUNCTION')
);

