CREATE TABLE [etlmanager].[Execution] (
    [ExecutionId]               UNIQUEIDENTIFIER    NOT NULL,
    [JobId]                     UNIQUEIDENTIFIER    NOT NULL,
    [JobName]                   NVARCHAR(250)       NOT NULL,
    [StepId]                    UNIQUEIDENTIFIER    NOT NULL,
    [StepName]                  NVARCHAR(250)       NOT NULL,
    [CreatedDateTime]           DATETIME2 (7)       NOT NULL,
    [RetryAttemptIndex]         INT                 NOT NULL,
    [StartDateTime]             DATETIME2 (7)       NULL,
    [EndDateTime]               DATETIME2 (7)       NULL,
    [ExecutionStatus]           VARCHAR(50)         NOT NULL,
    [RetryAttempts]             INT                 NOT NULL,
    [RetryIntervalMinutes]      INT                 NOT NULL,
    [TimeoutMinutes]            INT                 NOT NULL CONSTRAINT [DF_Execution_TimeoutMinutes] DEFAULT (0),
    [ExecutionInSeconds]        AS                  datediff(second,[StartDateTime],isnull([EndDateTime],getdate())),
    [ExecutionInMinutes]        AS                  datediff(minute,[StartDateTime],isnull([EndDateTime],getdate())),
    [ExecutionPhase]            INT                 NOT NULL,
    [DependencyMode]            BIT                 NOT NULL,
    [StepType]                  VARCHAR (20)        NOT NULL,
    [SqlStatement]              NVARCHAR (MAX)      NULL,
    [ConnectionId]              UNIQUEIDENTIFIER    NULL,
    [PackageFolderName]         NVARCHAR(128)       NULL,
    [PackageProjectName]        NVARCHAR(128)       NULL,
    [PackageName]               NVARCHAR(260)       NULL,
    [ExecuteIn32BitMode]        BIT                 NOT NULL,
    [PackageOperationId]        BIGINT              NULL,
    [DataFactoryId]             UNIQUEIDENTIFIER    NULL,
    [PipelineName]              NVARCHAR(250)       NULL,
    [PipelineRunId]             NVARCHAR(250)       NULL,
    [JobToExecuteId]            UNIQUEIDENTIFIER    NULL,
    [JobExecuteSynchronized]    BIT                 NULL,
    [ExeFileName]               NVARCHAR(1000)      NULL,
    [ExeArguments]              NVARCHAR(MAX)       NULL,
    [ExeWorkingDirectory]       NVARCHAR(1000)      NULL,
    [ExeSuccessExitCode]        INT                 NULL,
    [PowerBIServiceId]          UNIQUEIDENTIFIER    NULL,
    [DatasetGroupId]            NVARCHAR(36)        NULL,
    [DatasetId]                 NVARCHAR(36)        NULL,
    [ErrorMessage]              NVARCHAR(MAX)       NULL,
    [InfoMessage]               NVARCHAR(MAX)       NULL,
    [CreatedBy]                 NVARCHAR(250)       NULL,
    [StoppedBy]                 NVARCHAR(250)       NULL,
    [ScheduleId]                UNIQUEIDENTIFIER    NULL,
    [ExecutorProcessId]         INT                 NULL,
    CONSTRAINT [PK_Execution] PRIMARY KEY CLUSTERED ([ExecutionId] ASC, [StepId] ASC, [RetryAttemptIndex] ASC),
    CONSTRAINT [CK_Execution_StepType] CHECK ([StepType]='SSIS' OR [StepType]='SQL' OR [StepType]='JOB' OR [StepType]='PIPELINE' OR [StepType]='EXE' OR [StepType]='DATASET')
);

