CREATE TABLE [etlmanager].[StepTag]
(
	[StepsStepId] UNIQUEIDENTIFIER NOT NULL,
	[TagsTagId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_StepTag] PRIMARY KEY CLUSTERED ([StepsStepId], [TagsTagId]),
	CONSTRAINT [FK_StepTag_Step] FOREIGN KEY ([StepsStepId]) REFERENCES etlmanager.Step ([StepId]) ON DELETE CASCADE,
	CONSTRAINT [FK_StepTag_Tag] FOREIGN KEY ([TagsTagId]) REFERENCES etlmanager.Tag ([TagId]) ON DELETE CASCADE
)
