CREATE TABLE [etlmanager].[Tag]
(
	[TagId] UNIQUEIDENTIFIER NOT NULL,
	[TagName] NVARCHAR(250) NOT NULL,
	CONSTRAINT [PK_Tag] PRIMARY KEY CLUSTERED ([TagId]),
	CONSTRAINT [UQ_TagName] UNIQUE ([TagName])
)
