CREATE TABLE [biflow].[JobStepTagFilter]
(
	[StepId] UNIQUEIDENTIFIER NOT NULL,
	[TagId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_JobStepTag] PRIMARY KEY CLUSTERED ([StepId], [TagId]),
	CONSTRAINT [FK_JobStepTag_Step] FOREIGN KEY ([StepId]) REFERENCES biflow.Step ([StepId]) ON DELETE CASCADE,
	CONSTRAINT [FK_JobStepTag_Tag] FOREIGN KEY ([TagId]) REFERENCES biflow.Tag ([TagId]) ON DELETE CASCADE
)
