### Create environment version

POST {{baseUrl}}/environmentversions
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "description": "Test description"
}

### Revert by id

POST {{baseUrl}}/environmentversions/revert/25?retainIntegrationProperties=false
x-api-key: {{apiKey}}

### Get version revert status

GET {{baseUrl}}/environmentversions/revert/status/7308a4f5-9689-4e11-b099-0853a7877306
x-api-key: {{apiKey}}

### Revert to snapshot

POST {{baseUrl}}/environmentversions/revert?retainIntegrationProperties=false
x-api-key: {{apiKey}}
Content-Type: application/json

{
  
}