### Create job

POST {{baseUrl}}/jobs
x-api-key: {{apiKey}}
Content-Type: application/json

{
    "JobName": "API test job",
    "JobDescription": "Job created from API",
    "ExecutionMode": "ExecutionPhase",
    "StopOnFirstError": false,
    "MaxParallelSteps": 10,
    "OvertimeNotificationLimitMinutes": 0,
    "TimeoutMinutes": 0,
    "IsEnabled": true,
    "IsPinned": false,
    "JobTagIds": []
}

### Update job

PUT {{baseUrl}}/jobs/98ed48f1-4977-4c3c-c50b-08dd39ebf851
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "JobName": "API test job renamed",
  "JobDescription": "Job created from API",
  "ExecutionMode": "ExecutionPhase",
  "StopOnFirstError": true,
  "OvertimeNotificationLimitMinutes": 0,
  "TimeoutMinutes": 0,
  "JobTagIds": []
}

### Update job state

PATCH {{baseUrl}}/jobs/98ed48f1-4977-4c3c-c50b-08dd39ebf851/state
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "isEnabled": false
}

### Update job pinned

PATCH {{baseUrl}}/jobs/98ed48f1-4977-4c3c-c50b-08dd39ebf851/pinned
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "isPinned": true
}

### Update job parameters

PATCH {{baseUrl}}/jobs/98ed48f1-4977-4c3c-c50b-08dd39ebf851/parameters
x-api-key: {{apiKey}}
Content-Type: application/json

[
  {
    "parameterId": "10168487-55ed-4e84-9ff7-08dd55d097dd",
    "parameterName": "TestParam",
    "parameterValue": { "valueType": "String", "valueString": "hello world" },
    "useExpression": false,
    "expression": "DateTime.Now.ToString(\"o\")"
  },
  {
    "parameterId": null,
    "parameterName": "TestParam2",
    "parameterValue": { "valueType": "Int32", "valueInt32": 123 }
  }
]

### Update job concurrencies

PATCH {{baseUrl}}/jobs/98ed48f1-4977-4c3c-c50b-08dd39ebf851/concurrencies
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "maxParallelSteps": 12,
  "stepTypeConcurrencies": [
    { "stepType": "Sql", "maxParallelSteps": 4 },
    { "stepType": "Pipeline", "maxParallelSteps": 6 }
  ]
}

### Clear job concurrencies (empty array)

PATCH {{baseUrl}}/jobs/1fb73732-1083-4dc5-74ca-08dd39e8b1d4/concurrencies
x-api-key: {{apiKey}}
Content-Type: application/json

[]

### Create job tag

POST {{baseUrl}}/jobs/tags
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "tagName": "api-tag",
  "color": "DarkGray",
  "sortOrder": 10
}

### Update job tag

PUT {{baseUrl}}/jobs/tags/34d4fc01-db06-4dba-ad1b-08dd39e94479
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "tagName": "api-tag-updated",
  "color": "LightGray",
  "sortOrder": 10
}

### Create job tag relation

POST {{baseUrl}}/jobs/1fb73732-1083-4dc5-74ca-08dd39e8b1d4/tags/34d4fc01-db06-4dba-ad1b-08dd39e94479
x-api-key: {{apiKey}}

### Delete job tag relation

DELETE {{baseUrl}}/jobs/1fb73732-1083-4dc5-74ca-08dd39e8b1d4/tags/34d4fc01-db06-4dba-ad1b-08dd39e94479
x-api-key: {{apiKey}}

### Delete job tag

DELETE {{baseUrl}}/jobs/tags/34d4fc01-db06-4dba-ad1b-08dd39e94479
x-api-key: {{apiKey}}

### Delete job

DELETE {{baseUrl}}/jobs/1fb73732-1083-4dc5-74ca-08dd39e8b1d4
x-api-key: {{apiKey}}