### All jobs

GET {{baseUrl}}
    /jobs
    ?includeTags=true
x-api-key: {{apiKey}}

### Job by id

GET {{baseUrl}}
    /jobs
    /98ed48f1-4977-4c3c-c50b-08dd39ebf851
    ?includeParameters=true
    &includeConcurrencies=true
x-api-key: {{apiKey}}

### Job steps

GET {{baseUrl}}
    /jobs
    /29a43f41-d2e4-4e86-62a0-08dbb695de54
    /steps
    ?includeTags=true
x-api-key: {{apiKey}}

### Job schedules

GET {{baseUrl}}
    /jobs
    /29a43f41-d2e4-4e86-62a0-08dbb695de54
    /schedules
x-api-key: {{apiKey}}

### Job parameter by id

GET {{baseUrl}}/jobs/parameters/81b2bca5-3398-45b1-953e-08dc4fbd5e4c
x-api-key: {{apiKey}}

### All job tags

GET {{baseUrl}}/jobs/tags
x-api-key: {{apiKey}}

### Job tag by id

GET {{baseUrl}}/jobs/tags/bf390e86-58b1-4144-85aa-08dd22705f6a
x-api-key: {{apiKey}}

### All data objects

GET {{baseUrl}}/dataobjects
x-api-key: {{apiKey}}

### Data object by id

GET {{baseUrl}}/dataobjects/f927f054-8304-4b82-08d6-08dc66909c12
x-api-key: {{apiKey}}