### All schedules

GET {{baseUrl}}/jobs/schedules
x-api-key: {{apiKey}}

### All schedule tags

GET {{baseUrl}}/jobs/schedules/tags
x-api-key: {{apiKey}}

### Schedule by id

GET {{baseUrl}}/jobs/schedules/c2653eb7-0d37-4867-55bd-08dc608a0c2a
x-api-key: {{apiKey}}