### Step by id

GET {{baseUrl}}/jobs/steps/1919b753-096d-44ca-5df0-08dbb6cadb53
x-api-key: {{apiKey}}

### All step tags

GET {{baseUrl}}/jobs/steps/tags
x-api-key: {{apiKey}}

### Step tag by id

GET {{baseUrl}}/jobs/steps/tags/1002a70f-d3b6-463a-ab69-833024ac347c
x-api-key: {{apiKey}}