### All users

GET {{baseUrl}}/users
x-api-key: {{apiKey}}

### User by id

GET {{baseUrl}}/users/2d1ca49a-399d-4ad0-47fa-08dd4d24e5f8
x-api-key: {{apiKey}}

### User jobs

GET {{baseUrl}}/users/2d1ca49a-399d-4ad0-47fa-08dd4d24e5f8/jobs
x-api-key: {{apiKey}}

### User data tables

GET {{baseUrl}}/users/2d1ca49a-399d-4ad0-47fa-08dd4d24e5f8/datatables
x-api-key: {{apiKey}}

### User subscriptions

GET {{baseUrl}}/users/2d1ca49a-399d-4ad0-47fa-08dd4d24e5f8/subscriptions
x-api-key: {{apiKey}}