@API_KEY = 256155ff-f7f8-4da8-b449-0f147bb76c2b
@BASE_URL = http://localhost:6543/

### Start proxy task

POST {{BASE_URL}}/exe
x-api-key: {{API_KEY}}
Content-Type: application/json

{
  "exePath": "C:\\Users\\Tommi Hirvonen\\Desktop\\test.cmd",
  "arguments": null,
  "workingDirectory": null
}

### Get proxy task status

GET {{BASE_URL}}/exe/d718f6dd-ab37-44e4-808e-dd4cc2ee5973
x-api-key: {{API_KEY}}

### Cancel proxy task

POST {{BASE_URL}}/exe/d718f6dd-ab37-44e4-808e-dd4cc2ee5973/cancel
x-api-key: {{API_KEY}}